### PR TITLE
Fix issue where Grapher live view plots could overlap.

### PR DESCRIPTION
**Pull request by adamcw**
Fix for issue #154 where the plots on the Grapher live view could overlap if the page was less than the `450*num_plot` as each plot and its label require a minimum height to display.

The original implementation of `flex` would make each plot consistently 33% of the page when there were three plots, inconsiderate of minimum plot height.

This fix implements a minimum height, as well as applies the redraw function when plots are added so that plots are appropriately resized when new plots are added.

### CODE REVIEW

**Comment by joshm-3b6b58** [comment]
Are the live plots working for you? They're not working on my machine, everything in "live view" shows up empty when I start a new dataset. Also, live plots that do show up aren't scaling correctly for me. ~~~I've checked out some older commits and it seems to be broken as far back as 399f9dd for me...~~~

Edit: I must've broken it in 7b4f8a67 :(

**Comment by adamcw** [comment]
Live plots work just fine for me on master? That's where I branched this from.

**Comment by joshm-3b6b58** [comment]
Weird. They are not working for me at all. Let me do a gulp clean

**Comment by joshm-3b6b58** [comment]
OK I don't know what's going on, it works fine in one chrome window but not another. Pay no attention to my comments :|

**Comment by joshm-3b6b58** [comment]
I'm getting the following error on compilation:

```
app/scripts/activities.ts(235,9): error TS2341: Property 'plot' is private and only accessible within class 'DatasetActivity'.
app/scripts/activities.ts(235,9): error TS2341: Property 'redraw_' is private and only accessible within class 'Plot'.
```

**Comment by adamcw** [comment]
I guess those need to be public then, will fix.

**Comment by adamcw** [comment]
Made the required functions public, PR now compiles without errors or warnings.

**Comment by joshm-3b6b58** [comment]
So the formatting changes look really nice, but live view is utterly broken on my machine in weird ways. @maffoo does it work for you? I've managed to really confuse myself.

**Comment by adamcw** [comment]
To confirm, live view is broken on more than just this branch for you? What is "broken" about it?

**Comment by joshm-3b6b58** [comment]
It's broken in master.

When I got to live view and start a dataset running the nothing renders in the current plot. 

When I got to that specific dataset it shows points updating, but autoscales the graph wrong.

**Comment by maffoo** [comment]
I've had some strange behavior in the past that was fixed by completely removing the `bower_components` folder and rerunning `npm run bower install`. @joshmutus, you might try that.

**Comment by maffoo** [comment]
LGTM
